services:
  routing:
    image: ghcr.io/valhalla/valhalla-scripted@sha256:1bfd648c6140ed64d488eb1505bbff608749b39ea81be3f87d1220d253c200c0
    container_name: ezclick-valhalla-colorado
    restart: unless-stopped
    mem_limit: 6g
    cpus: 2
    ports:
      - "127.0.0.1:8002:8002"
    volumes:
      - ./data:/custom_files
    environment:
      tile_urls: https://download.geofabrik.de/north-america/us/colorado-latest.osm.pbf
      server_threads: "2"
      build_elevation: "False"
      build_transit: "False"
