import {createRoot} from 'react-dom/client';
import './base.css';
import '../app/fonts.css';
import WeatherMap from '../app/weather-map';
import WeatherDisclaimer from '../app/weather-disclaimer';
import './neon.css';
import weatherLogo from './assets/ez-click-weather-cropped-muted.webp';
const brandImage={src:weatherLogo,alt:'EZ Click Weather',width:800,height:308};
const path=window.location.pathname.replace(/\/$/,'');
createRoot(document.getElementById('root')!).render(path==='/terms'?<WeatherDisclaimer homeUrl="/" brandImage={brandImage}/>:<WeatherMap brandImage={brandImage}/>);
