'use client';
import {useEffect,useRef,useState,useId} from 'react';
import {Truck,Users,Play,Pause,Check,MessageCircle,Lightbulb,Bell,ChevronLeft,ChevronRight} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {frameUrl,clips} from './journey';
const staticPreview = process.env.NEXT_PUBLIC_STATIC_EXPORT === 'true';
const tour=[
 {clip:0,title:'Find your next move.',text:'Explore loads for your trailer. Compare the rate, miles and deadhead before you choose.'},
 {clip:1,title:'Know what you keep.',text:'Bring trip costs into the picture. Plan your route with a clear estimate of what remains.'},
 {clip:2,title:'Plan beyond this load.',text:'Explore Hot Zones, fuel options and weather along the way.'},
 {clip:5,title:'Keep the work moving.',text:'Discover the planned AI Dispatcher tools for matching loads and staying organized.'},
 {clip:12,title:'Every load. Every dollar.',text:'Keep documents, broker setup and driver statements together in one workflow.'},
 {clip:9,title:'Your business. Under control.',text:'EZCLICK GO is in development. Join the launch list and tell us what matters to you.'}
];
const faq=[
 ['Can I use EZCLICK GO today?','This site is an interactive preview. The application is still in development. You can explore demo features and join the launch list; app downloads and paid subscriptions are not available yet.'],
 ['Are these live loads?','No. The loads, rates, market indicators and calculations shown here are illustrative examples. Load-data sources and access arrangements are being finalized. No live DAT or Truckstop connection is claimed in this preview.'],
 ['What will Free include?','The planned Free tier includes three matching load offers at a time, the trip calculator and Driver Progress. Three at a time is a preview limit, not a lifetime limit of three loads. Launch availability and refresh rules will be confirmed before release.'],
 ['Is this for drivers or dispatchers?','Both. Drivers and owner-operators can focus on loads, costs and trip planning. Dispatchers and company owners can explore team workflows, broker setup, documents and statements. A plan unlocks tools; permissions determine access to company information.'],
 ['Which devices will be supported?','We are planning for iOS, Android, Windows and macOS. Availability and release dates will be announced when each version is ready. The website can be explored on a phone, tablet or computer.'],
 ['How will documents be protected?','Encrypted storage and transfer, two-factor sign-in and access permissions are planned for the application. These are not connected document-security services in this preview. Please do not send IDs, BOLs or other sensitive documents through the contact form.'],
 ['Do I need to pay to join the launch list?','No. Joining the list is free and does not start a subscription. The $19 Plus and $39 Pro monthly prices are previews; final features, limits and billing terms will be confirmed before purchase.']
];
export function SiteDetails({onExplore,onPricing,onJoin,onFaq,selectedPlan,joinRequest}:{onExplore:(index:number)=>void;onPricing:()=>void;onJoin:()=>void;onFaq:()=>void;selectedPlan:string;joinRequest:number}){
 const root=useRef<HTMLElement>(null),[audience,setAudience]=useState('solo'),[tourOpen,setTourOpen]=useState(false),[elapsed,setElapsed]=useState(0),[paused,setPaused]=useState(false);
 const [kind,setKind]=useState('launch'),[status,setStatus]=useState<'idle'|'saving'|'done'|'error'>('idle'),[error,setError]=useState('');
 const requestId=useRef(''),prefix=useId();
 const frame=Math.min(5,Math.floor(elapsed/10)),slide=tour[frame];
 useEffect(()=>{const el=root.current;if(!el)return;const items=el.querySelectorAll('.info-reveal');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;items.forEach(x=>x.classList.add('info-pending'));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('info-pending');observer.unobserve(e.target);}}),{threshold:.08});items.forEach(x=>observer.observe(x));return()=>{observer.disconnect();items.forEach(x=>x.classList.remove('info-pending'));};},[]);
 useEffect(()=>{if(!tourOpen||paused||elapsed>=60)return;const timer=setInterval(()=>setElapsed(x=>Math.min(60,x+.25)),250);return()=>clearInterval(timer);},[tourOpen,paused,elapsed>=60]);
 useEffect(()=>{const hide=()=>{if(document.hidden)setPaused(true);};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide);},[]);
 const chooseKind=(next:string)=>{setKind(next);setStatus('idle');setError('');requestId.current='';};
 useEffect(()=>{chooseKind('launch');},[selectedPlan,joinRequest]);
 const startTour=()=>{setElapsed(0);setPaused(matchMedia('(prefers-reduced-motion: reduce)').matches);setTourOpen(true);};
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{
  e.preventDefault();if(staticPreview || status==='saving')return;const form=e.currentTarget,data=new FormData(form);setStatus('saving');setError('');if(!requestId.current)requestId.current=crypto.randomUUID();
  try{const response=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,email:data.get('email'),role:data.get('role'),message:data.get('message')||'',kind,plan:selectedPlan,consent:data.get('consent')==='on',website:data.get('website')})});const result=await response.json() as {ok?:boolean;error?:string};if(!response.ok)throw new Error(result.error||'Please try again.');setStatus('done');form.reset();requestId.current='';}catch(error){setError(error instanceof Error?error.message:'Unable to save. Please try again.');setStatus('error');}
 };
 return <section className="site-details" ref={root} aria-label="Discover EZCLICK GO and get in touch">
  <div className="details-inner">
   <section className="audience-section info-reveal" aria-labelledby="audience-title"><div className="info-heading"><p className="eyebrow">BUILT AROUND YOUR DAY</p><h2 id="audience-title">Your road.<br/><span>Your way of working.</span></h2></div>
    <div className="audience-tabs" role="group" aria-label="Who are you exploring for?"><button aria-pressed={audience==='solo'} onClick={()=>setAudience('solo')}><Truck size={18}/>For myself</button><button aria-pressed={audience==='team'} onClick={()=>setAudience('team')}><Users size={18}/>For my team</button></div>
    <div className="audience-panel info-glass" key={audience}><div><span className="info-kicker">{audience==='solo'?'DRIVERS & OWNER-OPERATORS':'DISPATCHERS & COMPANY OWNERS'}</span><h3>{audience==='solo'?'Make every mile count.':'Keep everyone moving together.'}</h3><p>{audience==='solo'?'Find the loads that fit your truck, understand trip costs and plan your next move.':'Bring loads, broker setup, documents and driver statements into one workflow.'}</p></div><div><ul>{(audience==='solo'?['Find Load & trip calculator','Hot Zones, fuel & route weather','Your trip history & Driver Progress']:['AI Dispatcher & load planning','Broker checks & Quick Setup','Documents & driver statements']).map(text=><li key={text}><Check size={17}/>{text}</li>)}</ul><div className="info-actions"><button className="info-button" onClick={()=>onExplore(audience==='solo'?1:8)}>Explore the features</button><button className="info-text-button" onClick={onPricing}>Compare plans</button></div></div></div>
   </section>
   <section className="quick-overview info-glass info-reveal" aria-labelledby="quick-title"><div><span className="info-kicker">THE BIG PICTURE</span><h2 id="quick-title">One minute.<br/>A clearer picture.</h2><p>Take a guided look at what EZCLICK GO is being built to do.</p></div><button className="tour-launch" onClick={startTour}><span className="tour-play"><Play size={23}/></span><span><strong>Watch the 60-second overview</strong><small>Six chapters · Pause or explore at your pace</small></span></button></section>
   <section id="faq" className="faq-section info-reveal" aria-labelledby="faq-title"><div className="info-heading"><p className="eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</p><h2 id="faq-title">Before you get rolling.</h2></div><Accordion type="single" collapsible className="site-faq info-glass">{faq.map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
   <section id="contact" className="contact-section info-reveal" aria-labelledby="contact-title"><div className="contact-copy"><p className="eyebrow">LET’S BUILD THE ROAD AHEAD</p><h2 id="contact-title">Your next move.<br/><span>Starts here.</span></h2><p>Hear about the launch, ask a question or share an idea from your working day.</p><p className="contact-small">No payment. No documents to upload.<br/>Just a way to stay in touch.</p></div><div className="contact-card info-glass">
    <div className="contact-tabs" role="group" aria-label="Reason for contacting us">{[{id:'launch',name:'Launch updates',Icon:Bell},{id:'question',name:'Ask a question',Icon:MessageCircle},{id:'idea',name:'Suggest a feature',Icon:Lightbulb}].map(({id,name,Icon})=><button key={id} disabled={status==='saving'} aria-pressed={kind===id} onClick={()=>chooseKind(id)}><Icon size={17}/><span>{name}</span></button>)}</div>
    {staticPreview?<div className="contact-success" role="status"><Bell size={30}/><h3>Stay tuned.</h3><p>Launch registration and messaging are not available on this preview yet. Please check back for updates.</p><button className="info-button" onClick={()=>onExplore(1)}>Explore the features</button></div>:status==='done'?<div className="contact-success" role="status"><Check size={30}/><h3>{kind==='launch'?"You’re on the launch list.":'Thank you. Your message is saved.'}</h3><p>{kind==='launch'?"We’ll use your email for EZCLICK GO launch updates.":'The team can review your message and reply using the email you provided.'}</p><button className="info-button" onClick={()=>chooseKind(kind)}>Send another request</button></div>:<form onSubmit={submit} className="contact-form">
     {kind==='launch'&&selectedPlan!=='Undecided'&&<p className="form-plan">Interested in {selectedPlan} · No subscription started</p>}
     <label htmlFor={`${prefix}-email`}>Your email</label><input id={`${prefix}-email`} name="email" type="email" autoComplete="email" maxLength={254} required placeholder="you@company.com"/>
     <fieldset className="contact-roles"><legend>I’m a</legend>{[['driver','Driver'],['owner','Owner-operator / company owner'],['dispatcher','Dispatcher']].map(([value,label])=><label key={value}><input type="radio" name="role" value={value} required/>{label}</label>)}</fieldset>
     <label htmlFor={`${prefix}-message`}>{kind==='launch'?'What matters to you? (optional)':kind==='question'?'Your question':'Your idea'}</label><textarea id={`${prefix}-message`} name="message" rows={3} maxLength={2000} minLength={kind==='launch'?undefined:5} required={kind!=='launch'} placeholder={kind==='launch'?'Tell us what would help on your next trip.':'Tell us a little more…'}/>
     <div className="contact-trap" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
     <label className="contact-consent"><input type="checkbox" name="consent" required/><span>I agree to use of my email and message to {kind==='launch'?'send EZCLICK GO launch updates':'respond to this request'}. I can request removal using this form.</span></label>
     <p className="contact-privacy">Your details are stored with this site for the EZCLICK GO team. Do not include IDs, payment details or shipment documents.</p>
     {error&&<p className="contact-error" role="alert">{error}</p>}<button className="info-button contact-submit" disabled={status==='saving'}>{status==='saving'?'Saving…':kind==='launch'?'Notify me at launch':'Send message'}</button>
    </form>}
   </div></section>
   <footer className="info-footer"><span>EZCLICK GO <small>Built for the road ahead.</small></span><div><a href="#faq" onClick={e=>{e.preventDefault();onFaq();}}>FAQ</a><a href="#contact" onClick={e=>{e.preventDefault();chooseKind('question');onJoin();}}>Contact</a><button onClick={onPricing}>Pricing</button></div><p>Product preview · App releases and final plan details to be announced.</p></footer>
  </div>
  <Dialog open={tourOpen} onOpenChange={setTourOpen}><DialogContent className="overview-dialog"><DialogTitle className="sr-only">EZCLICK GO 60-second overview</DialogTitle><DialogDescription className="sr-only">Six chapters introduce the planned platform. Pause or use the previous and next buttons.</DialogDescription><div className="tour-scene" key={frame}><img src={frameUrl(slide.clip,Math.min(60,clips[slide.clip].frames-1))} alt=""/><div className="tour-shade"/><div className="tour-copy"><span>EZCLICK GO · {String(frame+1).padStart(2,'0')} / 06</span><h3>{slide.title}</h3><p>{slide.text}</p>{frame===5&&<button className="info-button" onClick={()=>{setTourOpen(false);chooseKind('launch');onJoin();}}>Join the launch list</button>}</div></div><div className="tour-bottom"><div className="tour-progress" aria-hidden="true">{tour.map((_,i)=><span key={i}><i style={{width:`${Math.max(0,Math.min(1,(elapsed-i*10)/10))*100}%`}}/></span>)}</div><div className="tour-controls"><button aria-label="Previous chapter" disabled={frame===0} onClick={()=>setElapsed(Math.max(0,(frame-1)*10))}><ChevronLeft size={20}/></button><button onClick={()=>{if(elapsed>=60){setElapsed(0);setPaused(false);}else setPaused(!paused);}}>{paused||elapsed>=60?<Play size={18}/>:<Pause size={18}/>} {elapsed>=60?'Replay':paused?'Play':'Pause'}</button><button aria-label="Next chapter" disabled={frame===5} onClick={()=>setElapsed(Math.min(50,(frame+1)*10))}><ChevronRight size={20}/></button><span>{Math.floor(elapsed)} / 60 sec</span></div></div></DialogContent></Dialog>
 </section>;
}
