import './weather-disclaimer.css';
import {platformBrandImage,type WeatherBrandImage} from './weather-brand';
export default function WeatherDisclaimer({homeUrl="https://weather.ezclickgo.com/",brandImage=platformBrandImage}:{homeUrl?:string;brandImage?:WeatherBrandImage}={}){
 return <main className="weather-legal-page">
  <header><a href="https://ezclickgo.com/"><img src={brandImage.src} width={brandImage.width} height={brandImage.height} alt={brandImage.alt}/></a><a href={homeUrl}>Back to weather map</a></header>
  <article><p className="legal-eyebrow">SERVICE INFORMATION</p><h1>Weather Information Disclaimer</h1><p className="legal-intro">Understand the limits of the weather information shown in EZCLICK GO.</p>
  <section><h2>Forecasts are estimates</h2><p>Weather information is provided for general information and trip planning. Forecasts and model estimates may differ from actual conditions at a particular location or time. They are not a guarantee of the weather you will encounter.</p></section>
  <section><h2>Data may be delayed or incomplete</h2><p>EZCLICK GO uses third-party weather and map data. Updates may be delayed, coverage may be limited, and information may contain errors or omissions. We do not guarantee the accuracy, completeness, timeliness, or uninterrupted availability of this information.</p></section>
  <section><h2>A clear map does not guarantee a clear road</h2><p>The absence of rain, snow, strong wind, or other hazards on the map does not establish that those conditions are absent. Some hazards and local conditions may not be represented. Animated transitions are visual interpolations between forecast frames, not additional observations.</p></section>
  <section><h2>Use additional sources for safety decisions</h2><p>Do not rely on EZCLICK GO as your sole source for driving or other safety-critical decisions. Check official weather alerts, road closures, travel restrictions, and current conditions. Follow instructions from local authorities and use your judgment about whether travel is safe.</p><p>The weather map is not an emergency warning service and does not certify that a road or route is safe or suitable for your vehicle.</p></section>
  <section><h2>Official information</h2><p>For U.S. weather forecasts and warnings, visit the <a href="https://www.weather.gov/" target="_blank" rel="noreferrer">National Weather Service</a>. Consult the relevant state transportation department or 511 service for road conditions and restrictions.</p></section>
  <section><h2>Contact support</h2><p>Use “Report a problem” in the weather map menu, or email <a href="mailto:support@ezclickgo.com">support@ezclickgo.com</a>. An optional reply address helps us follow up. You can review and turn off technical details before submitting; these include browser and device type, app version and interface settings. Route locations, voice recordings and precise location are not collected by the report form.</p><p>Reports are emailed to EZ Click Support and a server copy is retained for up to 30 days. Email copies remain in our support mailbox for handling your request. If you choose the optional AI-assisted review, your description, language and device operating system (when shared) are sent to OpenAI to suggest a summary, priority and possible duplicates. The reply-email field is excluded; contact details, links and coordinate patterns in the description are filtered where recognized, but please keep sensitive information out of the text. For duplicate detection, OpenAI also receives up to eight filtered summaries and ticket IDs from other reports whose authors chose AI review. AI drafts are unverified suggestions for our team and are deleted with the server report. Please do not include passwords or sensitive information in your description.</p></section>
  <p className="legal-note">These limitations apply only to the extent permitted by applicable law and do not exclude any rights or responsibilities that cannot lawfully be excluded.</p>
  </article><footer><a href={homeUrl}>Return to the map</a><span>EZCLICK GO</span></footer>
 </main>;
}
