from pathlib import Path
import json
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.pagesizes import A4
root=Path(__file__).resolve().parent.parent
d=json.loads((root/'app/statement-data.json').read_text())
for name,file in [('Inter','brand-0.ttf'),('InterBold','brand-2.ttf')]:pdfmetrics.registerFont(TTFont(name,str(root/'public/fonts'/file)))
c=canvas.Canvas(str(root/'public/downloads/ezclick-statement-demo.pdf'),pagesize=A4);w,h=A4;c.setTitle('EZCLICK - Sample Driver Settlement Statement')
navy=HexColor('#123a5b');line=HexColor('#c8daea');pale=HexColor('#edf3fa')
def text(x,y,s,size=9,bold=False):c.setFillColor(navy);c.setFont('InterBold' if bold else 'Inter',size);c.drawString(x,y,str(s))
def right(x,y,s,size=9,bold=False):c.setFillColor(navy);c.setFont('InterBold' if bold else 'Inter',size);c.drawRightString(x,y,str(s))
def box(x,y,ww,hh):c.setStrokeColor(line);c.setFillColor(pale);c.roundRect(x,y,ww,hh,9,fill=1,stroke=1)
def cash(v):return f'${v:,.2f}' if v>=0 else f'-${-v:,.2f}'
text(36,799,'EZCLICK',23,True);text(36,781,'TRUCKING MADE SIMPLE',8);box(375,767,184,50);text(390,799,'Statement #',8);text(390,780,d['number'],11,True);text(498,799,'Date',8);text(498,780,d['date'],10,True)
text(36,735,'Driver Settlement Statement',18,True);text(36,719,'SETTLEMENT DETAILS AND PAYMENT INFORMATION',8)
box(36,613,523,92)
for i,(label,val) in enumerate([('Driver',d['driver']),('Driver ID',d['driverId']),('Truck unit',d['truckUnit']),('Pay basis','30% of load rate')]):text(49,686-i*19,label+':',9);text(127,686-i*19,val,9,True)
for i,(label,val) in enumerate([('Pay to',d['payTo']),('Truck',d['truck']),('Trailer unit',d['trailerUnit']),('Equipment',d['equipment'])]):text(303,686-i*19,label+':',9);text(370,686-i*19,val,8.5,True)
text(43,591,'Loads',12,True);xs=[44,87,140,193,370,411,481,549];headers=['Load #','Pickup','Delivery','Description','Empty','Loaded','Rate','Amount'];c.setFillColor(pale);c.rect(36,563,523,19,fill=1,stroke=0)
for i,name in enumerate(headers): (right if i>3 else text)(xs[i],569,name,7.5,True)
y=546
for load in d['loads']:
 vals=[load['id'],load['pickup'],load['delivery'],load['route'].replace('→','to'),load['empty'],load['loaded'],cash(load['gross']),cash(load['gross']*d['share'])]
 for i,v in enumerate(vals):(right if i>3 else text)(xs[i],y,v,7.1)
 c.setStrokeColor(line);c.line(36,y-10,559,y-10);y-=26
subtotal=sum(l['gross']*d['share'] for l in d['loads']);ded=sum(x['amount'] for x in d['deductions']);net=subtotal-d['fuel']-ded
right(470,382,'Loads Subtotal',9);right(549,382,cash(subtotal),9,True)
text(43,350,'Fuel',12,True);text(44,329,'Date',8,True);text(140,329,'Description',8,True);right(549,329,'Amount',8,True);text(44,308,d['date']);text(140,308,'Fuel');right(549,308,cash(d['fuel']));right(470,289,'Fuel Subtotal');right(549,289,cash(d['fuel']),9,True)
text(43,259,'Deductions',12,True);text(44,240,'Date',8,True);text(140,240,'Description',8,True);right(549,240,'Amount',8,True)
for i,item in enumerate(d['deductions']):
 y=219-i*19;text(44,y,d['date'],8);text(140,y,item['name'],8);right(549,y,cash(-item['amount']),8)
right(470,142,'Deductions Subtotal');right(549,142,cash(ded),9,True)
c.setFillColor(navy);c.roundRect(36,68,523,53,10,fill=1,stroke=0);c.setFillColor(HexColor('#ffffff'));c.setFont('Inter',9);c.drawString(51,103,'Statement Total');c.drawString(319,103,'Balance Due');c.setFont('InterBold',18);c.drawString(51,80,cash(net));c.drawString(319,80,cash(net))
text(36,53,'YTD Gross Earnings: '+cash(d['ytd']),8);text(36,37,'DEMO - Illustrative figures. Not a payment record.',8);text(36,22,'Generated by EZCLICK',7);right(559,22,'1 / 1',7);c.save();assert net==4395
